// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PokemonGoApi.Proto {

  /// <summary>Holder for reflection information generated from communication.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class CommunicationReflection {

    #region Descriptor
    /// <summary>File descriptor for communication.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommunicationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNjb21tdW5pY2F0aW9uLnByb3RvEhJQb2tlbW9uR29BcGkuUHJvdG8iPAoL",
            "VW5rbm93bkF1dGgSDQoFc3RhcnQYASABKAwSEQoJdGltZXN0YW1wGAIgASgE",
            "EgsKA2VuZBgDIAEoDCKpBQoOUmVxdWVzdEVudmVsb3ASMAoJZGlyZWN0aW9u",
            "GAEgASgOMh0uUG9rZW1vbkdvQXBpLlByb3RvLkRpcmVjdGlvbhIOCgZycGNf",
            "aWQYAyABKAMSLQoIcmVxdWVzdHMYBCADKAsyGy5Qb2tlbW9uR29BcGkuUHJv",
            "dG8uUmVxdWVzdBI9Cgh1bmtub3duNhgGIAEoCzIrLlBva2Vtb25Hb0FwaS5Q",
            "cm90by5SZXF1ZXN0RW52ZWxvcC5Vbmtub3duNhIQCghsYXRpdHVkZRgHIAEo",
            "ARIRCglsb25naXR1ZGUYCCABKAESEAoIYWx0aXR1ZGUYCSABKAESOQoEYXV0",
            "aBgKIAEoCzIrLlBva2Vtb25Hb0FwaS5Qcm90by5SZXF1ZXN0RW52ZWxvcC5B",
            "dXRoSW5mbxI0Cgt1bmtub3duQXV0aBgLIAEoCzIfLlBva2Vtb25Hb0FwaS5Q",
            "cm90by5Vbmtub3duQXV0aBIRCgl1bmtub3duMTIYDCABKAMaHAoIVW5rbm93",
            "bjMSEAoIdW5rbm93bjQYASABKAkaggEKCFVua25vd242EhAKCHVua25vd24x",
            "GAEgASgFEkYKCHVua25vd24yGAIgASgLMjQuUG9rZW1vbkdvQXBpLlByb3Rv",
            "LlJlcXVlc3RFbnZlbG9wLlVua25vd242LlVua25vd24yGhwKCFVua25vd24y",
            "EhAKCHVua25vd24xGAEgASgMGogBCghBdXRoSW5mbxIQCghwcm92aWRlchgB",
            "IAEoCRI+CgV0b2tlbhgCIAEoCzIvLlBva2Vtb25Hb0FwaS5Qcm90by5SZXF1",
            "ZXN0RW52ZWxvcC5BdXRoSW5mby5KV1QaKgoDSldUEhAKCGNvbnRlbnRzGAEg",
            "ASgJEhEKCXVua25vd24xMxgCIAEoBSLwAgoPUmVzcG9uc2VFbnZlbG9wEhAK",
            "CHVua25vd24xGAEgASgFEhAKCHVua25vd24yGAIgASgDEg8KB2FwaV91cmwY",
            "AyABKAkSPgoIdW5rbm93bjYYBiABKAsyLC5Qb2tlbW9uR29BcGkuUHJvdG8u",
            "UmVzcG9uc2VFbnZlbG9wLlVua25vd242EjQKC3Vua25vd25BdXRoGAcgASgL",
            "Mh8uUG9rZW1vbkdvQXBpLlByb3RvLlVua25vd25BdXRoEiwKB3BheWxvYWQY",
            "ZCADKAsyGy5Qb2tlbW9uR29BcGkuUHJvdG8uUGF5bG9hZBqDAQoIVW5rbm93",
            "bjYSEAoIdW5rbm93bjEYASABKAUSRwoIdW5rbm93bjIYAiABKAsyNS5Qb2tl",
            "bW9uR29BcGkuUHJvdG8uUmVzcG9uc2VFbnZlbG9wLlVua25vd242LlVua25v",
            "d24yGhwKCFVua25vd24yEhAKCHVua25vd24xGAEgASgMIkEKB1JlcXVlc3QS",
            "KAoEdHlwZRgBIAEoDjIaLlBva2Vtb25Hb0FwaS5Qcm90by5NZXRob2QSDAoE",
            "ZGF0YRgCIAEoDCInCgdQYXlsb2FkEg4KBnVrbm93bhgBIAEoBRIMCgRkYXRh",
            "GAIgASgMKrwMCgZNZXRob2QSEAoMTUVUSE9EX1VOU0VUEAASEQoNUExBWUVS",
            "X1VQREFURRABEg4KCkdFVF9QTEFZRVIQAhIRCg1HRVRfSU5WRU5UT1JZEAQS",
            "FQoRRE9XTkxPQURfU0VUVElOR1MQBRIbChdET1dOTE9BRF9JVEVNX1RFTVBM",
            "QVRFUxAGEiIKHkRPV05MT0FEX1JFTU9URV9DT05GSUdfVkVSU0lPThAHEg8K",
            "C0ZPUlRfU0VBUkNIEGUSDQoJRU5DT1VOVEVSEGYSEQoNQ0FUQ0hfUE9LRU1P",
            "ThBnEhAKDEZPUlRfREVUQUlMUxBoEgwKCElURU1fVVNFEGkSEwoPR0VUX01B",
            "UF9PQkpFQ1RTEGoSFwoTRk9SVF9ERVBMT1lfUE9LRU1PThBuEhcKE0ZPUlRf",
            "UkVDQUxMX1BPS0VNT04QbxITCg9SRUxFQVNFX1BPS0VNT04QcBITCg9VU0Vf",
            "SVRFTV9QT1RJT04QcRIUChBVU0VfSVRFTV9DQVBUVVJFEHISEQoNVVNFX0lU",
            "RU1fRkxFRRBzEhMKD1VTRV9JVEVNX1JFVklWRRB0EhAKDFRSQURFX1NFQVJD",
            "SBB1Eg8KC1RSQURFX09GRkVSEHYSEgoOVFJBREVfUkVTUE9OU0UQdxIQCgxU",
            "UkFERV9SRVNVTFQQeBIWChJHRVRfUExBWUVSX1BST0ZJTEUQeRIRCg1HRVRf",
            "SVRFTV9QQUNLEHoSEQoNQlVZX0lURU1fUEFDSxB7EhAKDEJVWV9HRU1fUEFD",
            "SxB8EhIKDkVWT0xWRV9QT0tFTU9OEH0SFAoQR0VUX0hBVENIRURfRUdHUxB+",
            "Eh8KG0VOQ09VTlRFUl9UVVRPUklBTF9DT01QTEVURRB/EhUKEExFVkVMX1VQ",
            "X1JFV0FSRFMQgAESGQoUQ0hFQ0tfQVdBUkRFRF9CQURHRVMQgQESEQoMVVNF",
            "X0lURU1fR1lNEIUBEhQKD0dFVF9HWU1fREVUQUlMUxCGARIVChBTVEFSVF9H",
            "WU1fQkFUVExFEIcBEg8KCkFUVEFDS19HWU0QiAESGwoWUkVDWUNMRV9JTlZF",
            "TlRPUllfSVRFTRCJARIYChNDT0xMRUNUX0RBSUxZX0JPTlVTEIoBEhYKEVVT",
            "RV9JVEVNX1hQX0JPT1NUEIsBEhsKFlVTRV9JVEVNX0VHR19JTkNVQkFUT1IQ",
            "jAESEAoLVVNFX0lOQ0VOU0UQjQESGAoTR0VUX0lOQ0VOU0VfUE9LRU1PThCO",
            "ARIWChFJTkNFTlNFX0VOQ09VTlRFUhCPARIWChFBRERfRk9SVF9NT0RJRklF",
            "UhCQARITCg5ESVNLX0VOQ09VTlRFUhCRARIhChxDT0xMRUNUX0RBSUxZX0RF",
            "RkVOREVSX0JPTlVTEJIBEhQKD1VQR1JBREVfUE9LRU1PThCTARIZChRTRVRf",
            "RkFWT1JJVEVfUE9LRU1PThCUARIVChBOSUNLTkFNRV9QT0tFTU9OEJUBEhAK",
            "C0VRVUlQX0JBREdFEJYBEhkKFFNFVF9DT05UQUNUX1NFVFRJTkdTEJcBEhUK",
            "EEdFVF9BU1NFVF9ESUdFU1QQrAISFgoRR0VUX0RPV05MT0FEX1VSTFMQrQIS",
            "HAoXR0VUX1NVR0dFU1RFRF9DT0RFTkFNRVMQkQMSHQoYQ0hFQ0tfQ09ERU5B",
            "TUVfQVZBSUxBQkxFEJIDEhMKDkNMQUlNX0NPREVOQU1FEJMDEg8KClNFVF9B",
            "VkFUQVIQlAMSFAoPU0VUX1BMQVlFUl9URUFNEJUDEhsKFk1BUktfVFVUT1JJ",
            "QUxfQ09NUExFVEUQlgMSFgoRTE9BRF9TUEFXTl9QT0lOVFMQ9AMSCQoERUNI",
            "TxCaBRIbChZERUJVR19VUERBVEVfSU5WRU5UT1JZELwFEhgKE0RFQlVHX0RF",
            "TEVURV9QTEFZRVIQvQUSFwoSU0ZJREFfUkVHSVNUUkFUSU9OEKAGEhUKEFNG",
            "SURBX0FDVElPTl9MT0cQoQYSGAoTU0ZJREFfQ0VSVElGSUNBVElPThCiBhIR",
            "CgxTRklEQV9VUERBVEUQowYSEQoMU0ZJREFfQUNUSU9OEKQGEhEKDFNGSURB",
            "X0RPV1NFUhClBhISCg1TRklEQV9DQVBUVVJFEKYGKjMKCURpcmVjdGlvbhIL",
            "CgdVTktOT1dOEAASDAoIUkVTUE9OU0UQARILCgdSRVFVRVNUEAJiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PokemonGoApi.Proto.Method), typeof(global::PokemonGoApi.Proto.Direction), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.UnknownAuth), global::PokemonGoApi.Proto.UnknownAuth.Parser, new[]{ "Start", "Timestamp", "End" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.RequestEnvelop), global::PokemonGoApi.Proto.RequestEnvelop.Parser, new[]{ "Direction", "RpcId", "Requests", "Unknown6", "Latitude", "Longitude", "Altitude", "Auth", "UnknownAuth", "Unknown12" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown3), global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown3.Parser, new[]{ "Unknown4" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6), global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6.Parser, new[]{ "Unknown1", "Unknown2" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6.Types.Unknown2), global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6.Types.Unknown2.Parser, new[]{ "Unknown1" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo), global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo.Parser, new[]{ "Provider", "Token" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo.Types.JWT), global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo.Types.JWT.Parser, new[]{ "Contents", "Unknown13" }, null, null, null)})}),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.ResponseEnvelop), global::PokemonGoApi.Proto.ResponseEnvelop.Parser, new[]{ "Unknown1", "Unknown2", "ApiUrl", "Unknown6", "UnknownAuth", "Payload" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6), global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6.Parser, new[]{ "Unknown1", "Unknown2" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6.Types.Unknown2), global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6.Types.Unknown2.Parser, new[]{ "Unknown1" }, null, null, null)})}),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.Request), global::PokemonGoApi.Proto.Request.Parser, new[]{ "Type", "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGoApi.Proto.Payload), global::PokemonGoApi.Proto.Payload.Parser, new[]{ "Uknown", "Data" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Method {
    [pbr::OriginalName("METHOD_UNSET")] Unset = 0,
    [pbr::OriginalName("PLAYER_UPDATE")] PlayerUpdate = 1,
    [pbr::OriginalName("GET_PLAYER")] GetPlayer = 2,
    [pbr::OriginalName("GET_INVENTORY")] GetInventory = 4,
    [pbr::OriginalName("DOWNLOAD_SETTINGS")] DownloadSettings = 5,
    [pbr::OriginalName("DOWNLOAD_ITEM_TEMPLATES")] DownloadItemTemplates = 6,
    [pbr::OriginalName("DOWNLOAD_REMOTE_CONFIG_VERSION")] DownloadRemoteConfigVersion = 7,
    [pbr::OriginalName("FORT_SEARCH")] FortSearch = 101,
    [pbr::OriginalName("ENCOUNTER")] Encounter = 102,
    [pbr::OriginalName("CATCH_POKEMON")] CatchPokemon = 103,
    [pbr::OriginalName("FORT_DETAILS")] FortDetails = 104,
    [pbr::OriginalName("ITEM_USE")] ItemUse = 105,
    [pbr::OriginalName("GET_MAP_OBJECTS")] GetMapObjects = 106,
    [pbr::OriginalName("FORT_DEPLOY_POKEMON")] FortDeployPokemon = 110,
    [pbr::OriginalName("FORT_RECALL_POKEMON")] FortRecallPokemon = 111,
    [pbr::OriginalName("RELEASE_POKEMON")] ReleasePokemon = 112,
    [pbr::OriginalName("USE_ITEM_POTION")] UseItemPotion = 113,
    [pbr::OriginalName("USE_ITEM_CAPTURE")] UseItemCapture = 114,
    [pbr::OriginalName("USE_ITEM_FLEE")] UseItemFlee = 115,
    [pbr::OriginalName("USE_ITEM_REVIVE")] UseItemRevive = 116,
    [pbr::OriginalName("TRADE_SEARCH")] TradeSearch = 117,
    [pbr::OriginalName("TRADE_OFFER")] TradeOffer = 118,
    [pbr::OriginalName("TRADE_RESPONSE")] TradeResponse = 119,
    [pbr::OriginalName("TRADE_RESULT")] TradeResult = 120,
    [pbr::OriginalName("GET_PLAYER_PROFILE")] GetPlayerProfile = 121,
    [pbr::OriginalName("GET_ITEM_PACK")] GetItemPack = 122,
    [pbr::OriginalName("BUY_ITEM_PACK")] BuyItemPack = 123,
    [pbr::OriginalName("BUY_GEM_PACK")] BuyGemPack = 124,
    [pbr::OriginalName("EVOLVE_POKEMON")] EvolvePokemon = 125,
    [pbr::OriginalName("GET_HATCHED_EGGS")] GetHatchedEggs = 126,
    [pbr::OriginalName("ENCOUNTER_TUTORIAL_COMPLETE")] EncounterTutorialComplete = 127,
    [pbr::OriginalName("LEVEL_UP_REWARDS")] LevelUpRewards = 128,
    [pbr::OriginalName("CHECK_AWARDED_BADGES")] CheckAwardedBadges = 129,
    [pbr::OriginalName("USE_ITEM_GYM")] UseItemGym = 133,
    [pbr::OriginalName("GET_GYM_DETAILS")] GetGymDetails = 134,
    [pbr::OriginalName("START_GYM_BATTLE")] StartGymBattle = 135,
    [pbr::OriginalName("ATTACK_GYM")] AttackGym = 136,
    [pbr::OriginalName("RECYCLE_INVENTORY_ITEM")] RecycleInventoryItem = 137,
    [pbr::OriginalName("COLLECT_DAILY_BONUS")] CollectDailyBonus = 138,
    [pbr::OriginalName("USE_ITEM_XP_BOOST")] UseItemXpBoost = 139,
    [pbr::OriginalName("USE_ITEM_EGG_INCUBATOR")] UseItemEggIncubator = 140,
    [pbr::OriginalName("USE_INCENSE")] UseIncense = 141,
    [pbr::OriginalName("GET_INCENSE_POKEMON")] GetIncensePokemon = 142,
    [pbr::OriginalName("INCENSE_ENCOUNTER")] IncenseEncounter = 143,
    [pbr::OriginalName("ADD_FORT_MODIFIER")] AddFortModifier = 144,
    [pbr::OriginalName("DISK_ENCOUNTER")] DiskEncounter = 145,
    [pbr::OriginalName("COLLECT_DAILY_DEFENDER_BONUS")] CollectDailyDefenderBonus = 146,
    [pbr::OriginalName("UPGRADE_POKEMON")] UpgradePokemon = 147,
    [pbr::OriginalName("SET_FAVORITE_POKEMON")] SetFavoritePokemon = 148,
    [pbr::OriginalName("NICKNAME_POKEMON")] NicknamePokemon = 149,
    [pbr::OriginalName("EQUIP_BADGE")] EquipBadge = 150,
    [pbr::OriginalName("SET_CONTACT_SETTINGS")] SetContactSettings = 151,
    [pbr::OriginalName("GET_ASSET_DIGEST")] GetAssetDigest = 300,
    [pbr::OriginalName("GET_DOWNLOAD_URLS")] GetDownloadUrls = 301,
    [pbr::OriginalName("GET_SUGGESTED_CODENAMES")] GetSuggestedCodenames = 401,
    [pbr::OriginalName("CHECK_CODENAME_AVAILABLE")] CheckCodenameAvailable = 402,
    [pbr::OriginalName("CLAIM_CODENAME")] ClaimCodename = 403,
    [pbr::OriginalName("SET_AVATAR")] SetAvatar = 404,
    [pbr::OriginalName("SET_PLAYER_TEAM")] SetPlayerTeam = 405,
    [pbr::OriginalName("MARK_TUTORIAL_COMPLETE")] MarkTutorialComplete = 406,
    [pbr::OriginalName("LOAD_SPAWN_POINTS")] LoadSpawnPoints = 500,
    [pbr::OriginalName("ECHO")] Echo = 666,
    [pbr::OriginalName("DEBUG_UPDATE_INVENTORY")] DebugUpdateInventory = 700,
    [pbr::OriginalName("DEBUG_DELETE_PLAYER")] DebugDeletePlayer = 701,
    [pbr::OriginalName("SFIDA_REGISTRATION")] SfidaRegistration = 800,
    [pbr::OriginalName("SFIDA_ACTION_LOG")] SfidaActionLog = 801,
    [pbr::OriginalName("SFIDA_CERTIFICATION")] SfidaCertification = 802,
    [pbr::OriginalName("SFIDA_UPDATE")] SfidaUpdate = 803,
    [pbr::OriginalName("SFIDA_ACTION")] SfidaAction = 804,
    [pbr::OriginalName("SFIDA_DOWSER")] SfidaDowser = 805,
    [pbr::OriginalName("SFIDA_CAPTURE")] SfidaCapture = 806,
  }

  public enum Direction {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("RESPONSE")] Response = 1,
    [pbr::OriginalName("REQUEST")] Request = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class UnknownAuth : pb::IMessage<UnknownAuth> {
    private static readonly pb::MessageParser<UnknownAuth> _parser = new pb::MessageParser<UnknownAuth>(() => new UnknownAuth());
    public static pb::MessageParser<UnknownAuth> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::PokemonGoApi.Proto.CommunicationReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public UnknownAuth() {
      OnConstruction();
    }

    partial void OnConstruction();

    public UnknownAuth(UnknownAuth other) : this() {
      start_ = other.start_;
      timestamp_ = other.timestamp_;
      end_ = other.end_;
    }

    public UnknownAuth Clone() {
      return new UnknownAuth(this);
    }

    /// <summary>Field number for the "start" field.</summary>
    public const int StartFieldNumber = 1;
    private pb::ByteString start_ = pb::ByteString.Empty;
    public pb::ByteString Start {
      get { return start_; }
      set {
        start_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 2;
    private ulong timestamp_;
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "end" field.</summary>
    public const int EndFieldNumber = 3;
    private pb::ByteString end_ = pb::ByteString.Empty;
    public pb::ByteString End {
      get { return end_; }
      set {
        end_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as UnknownAuth);
    }

    public bool Equals(UnknownAuth other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Start != other.Start) return false;
      if (Timestamp != other.Timestamp) return false;
      if (End != other.End) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Start.Length != 0) hash ^= Start.GetHashCode();
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      if (End.Length != 0) hash ^= End.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Start.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Start);
      }
      if (Timestamp != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Timestamp);
      }
      if (End.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(End);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Start.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Start);
      }
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      if (End.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(End);
      }
      return size;
    }

    public void MergeFrom(UnknownAuth other) {
      if (other == null) {
        return;
      }
      if (other.Start.Length != 0) {
        Start = other.Start;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      if (other.End.Length != 0) {
        End = other.End;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Start = input.ReadBytes();
            break;
          }
          case 16: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 26: {
            End = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class RequestEnvelop : pb::IMessage<RequestEnvelop> {
    private static readonly pb::MessageParser<RequestEnvelop> _parser = new pb::MessageParser<RequestEnvelop>(() => new RequestEnvelop());
    public static pb::MessageParser<RequestEnvelop> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::PokemonGoApi.Proto.CommunicationReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public RequestEnvelop() {
      OnConstruction();
    }

    partial void OnConstruction();

    public RequestEnvelop(RequestEnvelop other) : this() {
      direction_ = other.direction_;
      rpcId_ = other.rpcId_;
      requests_ = other.requests_.Clone();
      Unknown6 = other.unknown6_ != null ? other.Unknown6.Clone() : null;
      latitude_ = other.latitude_;
      longitude_ = other.longitude_;
      altitude_ = other.altitude_;
      Auth = other.auth_ != null ? other.Auth.Clone() : null;
      UnknownAuth = other.unknownAuth_ != null ? other.UnknownAuth.Clone() : null;
      unknown12_ = other.unknown12_;
    }

    public RequestEnvelop Clone() {
      return new RequestEnvelop(this);
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 1;
    private global::PokemonGoApi.Proto.Direction direction_ = 0;
    public global::PokemonGoApi.Proto.Direction Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "rpc_id" field.</summary>
    public const int RpcIdFieldNumber = 3;
    private long rpcId_;
    public long RpcId {
      get { return rpcId_; }
      set {
        rpcId_ = value;
      }
    }

    /// <summary>Field number for the "requests" field.</summary>
    public const int RequestsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::PokemonGoApi.Proto.Request> _repeated_requests_codec
        = pb::FieldCodec.ForMessage(34, global::PokemonGoApi.Proto.Request.Parser);
    private readonly pbc::RepeatedField<global::PokemonGoApi.Proto.Request> requests_ = new pbc::RepeatedField<global::PokemonGoApi.Proto.Request>();
    public pbc::RepeatedField<global::PokemonGoApi.Proto.Request> Requests {
      get { return requests_; }
    }

    /// <summary>Field number for the "unknown6" field.</summary>
    public const int Unknown6FieldNumber = 6;
    private global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6 unknown6_;
    public global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6 Unknown6 {
      get { return unknown6_; }
      set {
        unknown6_ = value;
      }
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 7;
    private double latitude_;
    public double Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 8;
    private double longitude_;
    public double Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    /// <summary>Field number for the "altitude" field.</summary>
    public const int AltitudeFieldNumber = 9;
    private double altitude_;
    public double Altitude {
      get { return altitude_; }
      set {
        altitude_ = value;
      }
    }

    /// <summary>Field number for the "auth" field.</summary>
    public const int AuthFieldNumber = 10;
    private global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo auth_;
    public global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo Auth {
      get { return auth_; }
      set {
        auth_ = value;
      }
    }

    /// <summary>Field number for the "unknownAuth" field.</summary>
    public const int UnknownAuthFieldNumber = 11;
    private global::PokemonGoApi.Proto.UnknownAuth unknownAuth_;
    public global::PokemonGoApi.Proto.UnknownAuth UnknownAuth {
      get { return unknownAuth_; }
      set {
        unknownAuth_ = value;
      }
    }

    /// <summary>Field number for the "unknown12" field.</summary>
    public const int Unknown12FieldNumber = 12;
    private long unknown12_;
    public long Unknown12 {
      get { return unknown12_; }
      set {
        unknown12_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as RequestEnvelop);
    }

    public bool Equals(RequestEnvelop other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Direction != other.Direction) return false;
      if (RpcId != other.RpcId) return false;
      if(!requests_.Equals(other.requests_)) return false;
      if (!object.Equals(Unknown6, other.Unknown6)) return false;
      if (Latitude != other.Latitude) return false;
      if (Longitude != other.Longitude) return false;
      if (Altitude != other.Altitude) return false;
      if (!object.Equals(Auth, other.Auth)) return false;
      if (!object.Equals(UnknownAuth, other.UnknownAuth)) return false;
      if (Unknown12 != other.Unknown12) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Direction != 0) hash ^= Direction.GetHashCode();
      if (RpcId != 0L) hash ^= RpcId.GetHashCode();
      hash ^= requests_.GetHashCode();
      if (unknown6_ != null) hash ^= Unknown6.GetHashCode();
      if (Latitude != 0D) hash ^= Latitude.GetHashCode();
      if (Longitude != 0D) hash ^= Longitude.GetHashCode();
      if (Altitude != 0D) hash ^= Altitude.GetHashCode();
      if (auth_ != null) hash ^= Auth.GetHashCode();
      if (unknownAuth_ != null) hash ^= UnknownAuth.GetHashCode();
      if (Unknown12 != 0L) hash ^= Unknown12.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Direction != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Direction);
      }
      if (RpcId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(RpcId);
      }
      requests_.WriteTo(output, _repeated_requests_codec);
      if (unknown6_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Unknown6);
      }
      if (Latitude != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Longitude);
      }
      if (Altitude != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Altitude);
      }
      if (auth_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Auth);
      }
      if (unknownAuth_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(UnknownAuth);
      }
      if (Unknown12 != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(Unknown12);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Direction != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Direction);
      }
      if (RpcId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RpcId);
      }
      size += requests_.CalculateSize(_repeated_requests_codec);
      if (unknown6_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown6);
      }
      if (Latitude != 0D) {
        size += 1 + 8;
      }
      if (Longitude != 0D) {
        size += 1 + 8;
      }
      if (Altitude != 0D) {
        size += 1 + 8;
      }
      if (auth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Auth);
      }
      if (unknownAuth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnknownAuth);
      }
      if (Unknown12 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown12);
      }
      return size;
    }

    public void MergeFrom(RequestEnvelop other) {
      if (other == null) {
        return;
      }
      if (other.Direction != 0) {
        Direction = other.Direction;
      }
      if (other.RpcId != 0L) {
        RpcId = other.RpcId;
      }
      requests_.Add(other.requests_);
      if (other.unknown6_ != null) {
        if (unknown6_ == null) {
          unknown6_ = new global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6();
        }
        Unknown6.MergeFrom(other.Unknown6);
      }
      if (other.Latitude != 0D) {
        Latitude = other.Latitude;
      }
      if (other.Longitude != 0D) {
        Longitude = other.Longitude;
      }
      if (other.Altitude != 0D) {
        Altitude = other.Altitude;
      }
      if (other.auth_ != null) {
        if (auth_ == null) {
          auth_ = new global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo();
        }
        Auth.MergeFrom(other.Auth);
      }
      if (other.unknownAuth_ != null) {
        if (unknownAuth_ == null) {
          unknownAuth_ = new global::PokemonGoApi.Proto.UnknownAuth();
        }
        UnknownAuth.MergeFrom(other.UnknownAuth);
      }
      if (other.Unknown12 != 0L) {
        Unknown12 = other.Unknown12;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            direction_ = (global::PokemonGoApi.Proto.Direction) input.ReadEnum();
            break;
          }
          case 24: {
            RpcId = input.ReadInt64();
            break;
          }
          case 34: {
            requests_.AddEntriesFrom(input, _repeated_requests_codec);
            break;
          }
          case 50: {
            if (unknown6_ == null) {
              unknown6_ = new global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6();
            }
            input.ReadMessage(unknown6_);
            break;
          }
          case 57: {
            Latitude = input.ReadDouble();
            break;
          }
          case 65: {
            Longitude = input.ReadDouble();
            break;
          }
          case 73: {
            Altitude = input.ReadDouble();
            break;
          }
          case 82: {
            if (auth_ == null) {
              auth_ = new global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo();
            }
            input.ReadMessage(auth_);
            break;
          }
          case 90: {
            if (unknownAuth_ == null) {
              unknownAuth_ = new global::PokemonGoApi.Proto.UnknownAuth();
            }
            input.ReadMessage(unknownAuth_);
            break;
          }
          case 96: {
            Unknown12 = input.ReadInt64();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the RequestEnvelop message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Unknown3 : pb::IMessage<Unknown3> {
        private static readonly pb::MessageParser<Unknown3> _parser = new pb::MessageParser<Unknown3>(() => new Unknown3());
        public static pb::MessageParser<Unknown3> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGoApi.Proto.RequestEnvelop.Descriptor.NestedTypes[0]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Unknown3() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Unknown3(Unknown3 other) : this() {
          unknown4_ = other.unknown4_;
        }

        public Unknown3 Clone() {
          return new Unknown3(this);
        }

        /// <summary>Field number for the "unknown4" field.</summary>
        public const int Unknown4FieldNumber = 1;
        private string unknown4_ = "";
        public string Unknown4 {
          get { return unknown4_; }
          set {
            unknown4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Unknown3);
        }

        public bool Equals(Unknown3 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unknown4 != other.Unknown4) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Unknown4.Length != 0) hash ^= Unknown4.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Unknown4.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Unknown4);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Unknown4.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Unknown4);
          }
          return size;
        }

        public void MergeFrom(Unknown3 other) {
          if (other == null) {
            return;
          }
          if (other.Unknown4.Length != 0) {
            Unknown4 = other.Unknown4;
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                Unknown4 = input.ReadString();
                break;
              }
            }
          }
        }

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Unknown6 : pb::IMessage<Unknown6> {
        private static readonly pb::MessageParser<Unknown6> _parser = new pb::MessageParser<Unknown6>(() => new Unknown6());
        public static pb::MessageParser<Unknown6> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGoApi.Proto.RequestEnvelop.Descriptor.NestedTypes[1]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Unknown6() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Unknown6(Unknown6 other) : this() {
          unknown1_ = other.unknown1_;
          Unknown2 = other.unknown2_ != null ? other.Unknown2.Clone() : null;
        }

        public Unknown6 Clone() {
          return new Unknown6(this);
        }

        /// <summary>Field number for the "unknown1" field.</summary>
        public const int Unknown1FieldNumber = 1;
        private int unknown1_;
        public int Unknown1 {
          get { return unknown1_; }
          set {
            unknown1_ = value;
          }
        }

        /// <summary>Field number for the "unknown2" field.</summary>
        public const int Unknown2FieldNumber = 2;
        private global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6.Types.Unknown2 unknown2_;
        public global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6.Types.Unknown2 Unknown2 {
          get { return unknown2_; }
          set {
            unknown2_ = value;
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Unknown6);
        }

        public bool Equals(Unknown6 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unknown1 != other.Unknown1) return false;
          if (!object.Equals(Unknown2, other.Unknown2)) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
          if (unknown2_ != null) hash ^= Unknown2.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Unknown1 != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Unknown1);
          }
          if (unknown2_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Unknown2);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Unknown1 != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown1);
          }
          if (unknown2_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown2);
          }
          return size;
        }

        public void MergeFrom(Unknown6 other) {
          if (other == null) {
            return;
          }
          if (other.Unknown1 != 0) {
            Unknown1 = other.Unknown1;
          }
          if (other.unknown2_ != null) {
            if (unknown2_ == null) {
              unknown2_ = new global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6.Types.Unknown2();
            }
            Unknown2.MergeFrom(other.Unknown2);
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 8: {
                Unknown1 = input.ReadInt32();
                break;
              }
              case 18: {
                if (unknown2_ == null) {
                  unknown2_ = new global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6.Types.Unknown2();
                }
                input.ReadMessage(unknown2_);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the Unknown6 message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
          public sealed partial class Unknown2 : pb::IMessage<Unknown2> {
            private static readonly pb::MessageParser<Unknown2> _parser = new pb::MessageParser<Unknown2>(() => new Unknown2());
            public static pb::MessageParser<Unknown2> Parser { get { return _parser; } }

            public static pbr::MessageDescriptor Descriptor {
              get { return global::PokemonGoApi.Proto.RequestEnvelop.Types.Unknown6.Descriptor.NestedTypes[0]; }
            }

            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            public Unknown2() {
              OnConstruction();
            }

            partial void OnConstruction();

            public Unknown2(Unknown2 other) : this() {
              unknown1_ = other.unknown1_;
            }

            public Unknown2 Clone() {
              return new Unknown2(this);
            }

            /// <summary>Field number for the "unknown1" field.</summary>
            public const int Unknown1FieldNumber = 1;
            private pb::ByteString unknown1_ = pb::ByteString.Empty;
            public pb::ByteString Unknown1 {
              get { return unknown1_; }
              set {
                unknown1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            public override bool Equals(object other) {
              return Equals(other as Unknown2);
            }

            public bool Equals(Unknown2 other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Unknown1 != other.Unknown1) return false;
              return true;
            }

            public override int GetHashCode() {
              int hash = 1;
              if (Unknown1.Length != 0) hash ^= Unknown1.GetHashCode();
              return hash;
            }

            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            public void WriteTo(pb::CodedOutputStream output) {
              if (Unknown1.Length != 0) {
                output.WriteRawTag(10);
                output.WriteBytes(Unknown1);
              }
            }

            public int CalculateSize() {
              int size = 0;
              if (Unknown1.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown1);
              }
              return size;
            }

            public void MergeFrom(Unknown2 other) {
              if (other == null) {
                return;
              }
              if (other.Unknown1.Length != 0) {
                Unknown1 = other.Unknown1;
              }
            }

            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    input.SkipLastField();
                    break;
                  case 10: {
                    Unknown1 = input.ReadBytes();
                    break;
                  }
                }
              }
            }

          }

        }
        #endregion

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class AuthInfo : pb::IMessage<AuthInfo> {
        private static readonly pb::MessageParser<AuthInfo> _parser = new pb::MessageParser<AuthInfo>(() => new AuthInfo());
        public static pb::MessageParser<AuthInfo> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGoApi.Proto.RequestEnvelop.Descriptor.NestedTypes[2]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public AuthInfo() {
          OnConstruction();
        }

        partial void OnConstruction();

        public AuthInfo(AuthInfo other) : this() {
          provider_ = other.provider_;
          Token = other.token_ != null ? other.Token.Clone() : null;
        }

        public AuthInfo Clone() {
          return new AuthInfo(this);
        }

        /// <summary>Field number for the "provider" field.</summary>
        public const int ProviderFieldNumber = 1;
        private string provider_ = "";
        public string Provider {
          get { return provider_; }
          set {
            provider_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "token" field.</summary>
        public const int TokenFieldNumber = 2;
        private global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo.Types.JWT token_;
        public global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo.Types.JWT Token {
          get { return token_; }
          set {
            token_ = value;
          }
        }

        public override bool Equals(object other) {
          return Equals(other as AuthInfo);
        }

        public bool Equals(AuthInfo other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Provider != other.Provider) return false;
          if (!object.Equals(Token, other.Token)) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Provider.Length != 0) hash ^= Provider.GetHashCode();
          if (token_ != null) hash ^= Token.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Provider.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Provider);
          }
          if (token_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Token);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Provider.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Provider);
          }
          if (token_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Token);
          }
          return size;
        }

        public void MergeFrom(AuthInfo other) {
          if (other == null) {
            return;
          }
          if (other.Provider.Length != 0) {
            Provider = other.Provider;
          }
          if (other.token_ != null) {
            if (token_ == null) {
              token_ = new global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo.Types.JWT();
            }
            Token.MergeFrom(other.Token);
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                Provider = input.ReadString();
                break;
              }
              case 18: {
                if (token_ == null) {
                  token_ = new global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo.Types.JWT();
                }
                input.ReadMessage(token_);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the AuthInfo message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
          public sealed partial class JWT : pb::IMessage<JWT> {
            private static readonly pb::MessageParser<JWT> _parser = new pb::MessageParser<JWT>(() => new JWT());
            public static pb::MessageParser<JWT> Parser { get { return _parser; } }

            public static pbr::MessageDescriptor Descriptor {
              get { return global::PokemonGoApi.Proto.RequestEnvelop.Types.AuthInfo.Descriptor.NestedTypes[0]; }
            }

            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            public JWT() {
              OnConstruction();
            }

            partial void OnConstruction();

            public JWT(JWT other) : this() {
              contents_ = other.contents_;
              unknown13_ = other.unknown13_;
            }

            public JWT Clone() {
              return new JWT(this);
            }

            /// <summary>Field number for the "contents" field.</summary>
            public const int ContentsFieldNumber = 1;
            private string contents_ = "";
            public string Contents {
              get { return contents_; }
              set {
                contents_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "unknown13" field.</summary>
            public const int Unknown13FieldNumber = 2;
            private int unknown13_;
            public int Unknown13 {
              get { return unknown13_; }
              set {
                unknown13_ = value;
              }
            }

            public override bool Equals(object other) {
              return Equals(other as JWT);
            }

            public bool Equals(JWT other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Contents != other.Contents) return false;
              if (Unknown13 != other.Unknown13) return false;
              return true;
            }

            public override int GetHashCode() {
              int hash = 1;
              if (Contents.Length != 0) hash ^= Contents.GetHashCode();
              if (Unknown13 != 0) hash ^= Unknown13.GetHashCode();
              return hash;
            }

            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            public void WriteTo(pb::CodedOutputStream output) {
              if (Contents.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(Contents);
              }
              if (Unknown13 != 0) {
                output.WriteRawTag(16);
                output.WriteInt32(Unknown13);
              }
            }

            public int CalculateSize() {
              int size = 0;
              if (Contents.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Contents);
              }
              if (Unknown13 != 0) {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown13);
              }
              return size;
            }

            public void MergeFrom(JWT other) {
              if (other == null) {
                return;
              }
              if (other.Contents.Length != 0) {
                Contents = other.Contents;
              }
              if (other.Unknown13 != 0) {
                Unknown13 = other.Unknown13;
              }
            }

            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    input.SkipLastField();
                    break;
                  case 10: {
                    Contents = input.ReadString();
                    break;
                  }
                  case 16: {
                    Unknown13 = input.ReadInt32();
                    break;
                  }
                }
              }
            }

          }

        }
        #endregion

      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class ResponseEnvelop : pb::IMessage<ResponseEnvelop> {
    private static readonly pb::MessageParser<ResponseEnvelop> _parser = new pb::MessageParser<ResponseEnvelop>(() => new ResponseEnvelop());
    public static pb::MessageParser<ResponseEnvelop> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::PokemonGoApi.Proto.CommunicationReflection.Descriptor.MessageTypes[2]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public ResponseEnvelop() {
      OnConstruction();
    }

    partial void OnConstruction();

    public ResponseEnvelop(ResponseEnvelop other) : this() {
      unknown1_ = other.unknown1_;
      unknown2_ = other.unknown2_;
      apiUrl_ = other.apiUrl_;
      Unknown6 = other.unknown6_ != null ? other.Unknown6.Clone() : null;
      UnknownAuth = other.unknownAuth_ != null ? other.UnknownAuth.Clone() : null;
      payload_ = other.payload_.Clone();
    }

    public ResponseEnvelop Clone() {
      return new ResponseEnvelop(this);
    }

    /// <summary>Field number for the "unknown1" field.</summary>
    public const int Unknown1FieldNumber = 1;
    private int unknown1_;
    public int Unknown1 {
      get { return unknown1_; }
      set {
        unknown1_ = value;
      }
    }

    /// <summary>Field number for the "unknown2" field.</summary>
    public const int Unknown2FieldNumber = 2;
    private long unknown2_;
    public long Unknown2 {
      get { return unknown2_; }
      set {
        unknown2_ = value;
      }
    }

    /// <summary>Field number for the "api_url" field.</summary>
    public const int ApiUrlFieldNumber = 3;
    private string apiUrl_ = "";
    public string ApiUrl {
      get { return apiUrl_; }
      set {
        apiUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unknown6" field.</summary>
    public const int Unknown6FieldNumber = 6;
    private global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6 unknown6_;
    public global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6 Unknown6 {
      get { return unknown6_; }
      set {
        unknown6_ = value;
      }
    }

    /// <summary>Field number for the "unknownAuth" field.</summary>
    public const int UnknownAuthFieldNumber = 7;
    private global::PokemonGoApi.Proto.UnknownAuth unknownAuth_;
    public global::PokemonGoApi.Proto.UnknownAuth UnknownAuth {
      get { return unknownAuth_; }
      set {
        unknownAuth_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 100;
    private static readonly pb::FieldCodec<global::PokemonGoApi.Proto.Payload> _repeated_payload_codec
        = pb::FieldCodec.ForMessage(802, global::PokemonGoApi.Proto.Payload.Parser);
    private readonly pbc::RepeatedField<global::PokemonGoApi.Proto.Payload> payload_ = new pbc::RepeatedField<global::PokemonGoApi.Proto.Payload>();
    public pbc::RepeatedField<global::PokemonGoApi.Proto.Payload> Payload {
      get { return payload_; }
    }

    public override bool Equals(object other) {
      return Equals(other as ResponseEnvelop);
    }

    public bool Equals(ResponseEnvelop other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Unknown1 != other.Unknown1) return false;
      if (Unknown2 != other.Unknown2) return false;
      if (ApiUrl != other.ApiUrl) return false;
      if (!object.Equals(Unknown6, other.Unknown6)) return false;
      if (!object.Equals(UnknownAuth, other.UnknownAuth)) return false;
      if(!payload_.Equals(other.payload_)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
      if (Unknown2 != 0L) hash ^= Unknown2.GetHashCode();
      if (ApiUrl.Length != 0) hash ^= ApiUrl.GetHashCode();
      if (unknown6_ != null) hash ^= Unknown6.GetHashCode();
      if (unknownAuth_ != null) hash ^= UnknownAuth.GetHashCode();
      hash ^= payload_.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Unknown1 != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Unknown1);
      }
      if (Unknown2 != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Unknown2);
      }
      if (ApiUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ApiUrl);
      }
      if (unknown6_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Unknown6);
      }
      if (unknownAuth_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(UnknownAuth);
      }
      payload_.WriteTo(output, _repeated_payload_codec);
    }

    public int CalculateSize() {
      int size = 0;
      if (Unknown1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown1);
      }
      if (Unknown2 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown2);
      }
      if (ApiUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApiUrl);
      }
      if (unknown6_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown6);
      }
      if (unknownAuth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnknownAuth);
      }
      size += payload_.CalculateSize(_repeated_payload_codec);
      return size;
    }

    public void MergeFrom(ResponseEnvelop other) {
      if (other == null) {
        return;
      }
      if (other.Unknown1 != 0) {
        Unknown1 = other.Unknown1;
      }
      if (other.Unknown2 != 0L) {
        Unknown2 = other.Unknown2;
      }
      if (other.ApiUrl.Length != 0) {
        ApiUrl = other.ApiUrl;
      }
      if (other.unknown6_ != null) {
        if (unknown6_ == null) {
          unknown6_ = new global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6();
        }
        Unknown6.MergeFrom(other.Unknown6);
      }
      if (other.unknownAuth_ != null) {
        if (unknownAuth_ == null) {
          unknownAuth_ = new global::PokemonGoApi.Proto.UnknownAuth();
        }
        UnknownAuth.MergeFrom(other.UnknownAuth);
      }
      payload_.Add(other.payload_);
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Unknown1 = input.ReadInt32();
            break;
          }
          case 16: {
            Unknown2 = input.ReadInt64();
            break;
          }
          case 26: {
            ApiUrl = input.ReadString();
            break;
          }
          case 50: {
            if (unknown6_ == null) {
              unknown6_ = new global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6();
            }
            input.ReadMessage(unknown6_);
            break;
          }
          case 58: {
            if (unknownAuth_ == null) {
              unknownAuth_ = new global::PokemonGoApi.Proto.UnknownAuth();
            }
            input.ReadMessage(unknownAuth_);
            break;
          }
          case 802: {
            payload_.AddEntriesFrom(input, _repeated_payload_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ResponseEnvelop message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Unknown6 : pb::IMessage<Unknown6> {
        private static readonly pb::MessageParser<Unknown6> _parser = new pb::MessageParser<Unknown6>(() => new Unknown6());
        public static pb::MessageParser<Unknown6> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGoApi.Proto.ResponseEnvelop.Descriptor.NestedTypes[0]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Unknown6() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Unknown6(Unknown6 other) : this() {
          unknown1_ = other.unknown1_;
          Unknown2 = other.unknown2_ != null ? other.Unknown2.Clone() : null;
        }

        public Unknown6 Clone() {
          return new Unknown6(this);
        }

        /// <summary>Field number for the "unknown1" field.</summary>
        public const int Unknown1FieldNumber = 1;
        private int unknown1_;
        public int Unknown1 {
          get { return unknown1_; }
          set {
            unknown1_ = value;
          }
        }

        /// <summary>Field number for the "unknown2" field.</summary>
        public const int Unknown2FieldNumber = 2;
        private global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6.Types.Unknown2 unknown2_;
        public global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6.Types.Unknown2 Unknown2 {
          get { return unknown2_; }
          set {
            unknown2_ = value;
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Unknown6);
        }

        public bool Equals(Unknown6 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unknown1 != other.Unknown1) return false;
          if (!object.Equals(Unknown2, other.Unknown2)) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
          if (unknown2_ != null) hash ^= Unknown2.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Unknown1 != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Unknown1);
          }
          if (unknown2_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Unknown2);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Unknown1 != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown1);
          }
          if (unknown2_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown2);
          }
          return size;
        }

        public void MergeFrom(Unknown6 other) {
          if (other == null) {
            return;
          }
          if (other.Unknown1 != 0) {
            Unknown1 = other.Unknown1;
          }
          if (other.unknown2_ != null) {
            if (unknown2_ == null) {
              unknown2_ = new global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6.Types.Unknown2();
            }
            Unknown2.MergeFrom(other.Unknown2);
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 8: {
                Unknown1 = input.ReadInt32();
                break;
              }
              case 18: {
                if (unknown2_ == null) {
                  unknown2_ = new global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6.Types.Unknown2();
                }
                input.ReadMessage(unknown2_);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the Unknown6 message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
          public sealed partial class Unknown2 : pb::IMessage<Unknown2> {
            private static readonly pb::MessageParser<Unknown2> _parser = new pb::MessageParser<Unknown2>(() => new Unknown2());
            public static pb::MessageParser<Unknown2> Parser { get { return _parser; } }

            public static pbr::MessageDescriptor Descriptor {
              get { return global::PokemonGoApi.Proto.ResponseEnvelop.Types.Unknown6.Descriptor.NestedTypes[0]; }
            }

            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            public Unknown2() {
              OnConstruction();
            }

            partial void OnConstruction();

            public Unknown2(Unknown2 other) : this() {
              unknown1_ = other.unknown1_;
            }

            public Unknown2 Clone() {
              return new Unknown2(this);
            }

            /// <summary>Field number for the "unknown1" field.</summary>
            public const int Unknown1FieldNumber = 1;
            private pb::ByteString unknown1_ = pb::ByteString.Empty;
            public pb::ByteString Unknown1 {
              get { return unknown1_; }
              set {
                unknown1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            public override bool Equals(object other) {
              return Equals(other as Unknown2);
            }

            public bool Equals(Unknown2 other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Unknown1 != other.Unknown1) return false;
              return true;
            }

            public override int GetHashCode() {
              int hash = 1;
              if (Unknown1.Length != 0) hash ^= Unknown1.GetHashCode();
              return hash;
            }

            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            public void WriteTo(pb::CodedOutputStream output) {
              if (Unknown1.Length != 0) {
                output.WriteRawTag(10);
                output.WriteBytes(Unknown1);
              }
            }

            public int CalculateSize() {
              int size = 0;
              if (Unknown1.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown1);
              }
              return size;
            }

            public void MergeFrom(Unknown2 other) {
              if (other == null) {
                return;
              }
              if (other.Unknown1.Length != 0) {
                Unknown1 = other.Unknown1;
              }
            }

            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    input.SkipLastField();
                    break;
                  case 10: {
                    Unknown1 = input.ReadBytes();
                    break;
                  }
                }
              }
            }

          }

        }
        #endregion

      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Request : pb::IMessage<Request> {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::PokemonGoApi.Proto.CommunicationReflection.Descriptor.MessageTypes[3]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Request(Request other) : this() {
      type_ = other.type_;
      data_ = other.data_;
    }

    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::PokemonGoApi.Proto.Method type_ = 0;
    public global::PokemonGoApi.Proto.Method Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private pb::ByteString data_ = pb::ByteString.Empty;
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Data != other.Data) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Data);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      return size;
    }

    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            type_ = (global::PokemonGoApi.Proto.Method) input.ReadEnum();
            break;
          }
          case 18: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Payload : pb::IMessage<Payload> {
    private static readonly pb::MessageParser<Payload> _parser = new pb::MessageParser<Payload>(() => new Payload());
    public static pb::MessageParser<Payload> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::PokemonGoApi.Proto.CommunicationReflection.Descriptor.MessageTypes[4]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Payload() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Payload(Payload other) : this() {
      uknown_ = other.uknown_;
      data_ = other.data_;
    }

    public Payload Clone() {
      return new Payload(this);
    }

    /// <summary>Field number for the "uknown" field.</summary>
    public const int UknownFieldNumber = 1;
    private int uknown_;
    public int Uknown {
      get { return uknown_; }
      set {
        uknown_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private pb::ByteString data_ = pb::ByteString.Empty;
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Payload);
    }

    public bool Equals(Payload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uknown != other.Uknown) return false;
      if (Data != other.Data) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Uknown != 0) hash ^= Uknown.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Uknown != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Uknown);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Data);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Uknown != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Uknown);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      return size;
    }

    public void MergeFrom(Payload other) {
      if (other == null) {
        return;
      }
      if (other.Uknown != 0) {
        Uknown = other.Uknown;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Uknown = input.ReadInt32();
            break;
          }
          case 18: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
